//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodSpecialsUI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HillBrosInc_FoodSpecialsEntities : DbContext
    {
        public HillBrosInc_FoodSpecialsEntities()
            : base("name=HillBrosInc_FoodSpecialsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<UserSpecialRating> UserSpecialRatings { get; set; }
        public virtual DbSet<FoodSpecial> FoodSpecials { get; set; }
    }
}
